### PR TITLE
[WIP] get ingredients, peanut butter

### LINKED ISSUE #1: need ingredients
- bread
- peanut butter
- jelly

### PR DESCRIPTION
**Pull request by ashleygwilliams**
WORK IN PROGRESS PLEASE DONT MERGE <3

fixes #1

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
sure @ag-dubs i'll try in a second.

**Comment by ashleygwilliams** [comment]
ok @ag-dubs i think this should be everything. what do you think?

**Comment by ag-dubs** [comment]
actually i think creamy peanut butter would be better? thanks.

**Comment by ashleygwilliams** [comment]
thoughts? @ag-dubs ?

**Comment by ag-dubs** [comment]
k. plz squash

**Comment by ag-dubs** [comment]
looks like you missed that last one, but otherwise this is good

**Comment by ashleygwilliams** [comment]
ok! should finally be done!

**Comment by ag-dubs** [comment]
looks great. merging!

**Pull request merged**
